name: Sync with Hugging Face Hub

on:
  push:
    branches:
      - dev_branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
        with:
          lfs: 'true'
    - name: Sync with Hugging Face
      uses: nateraw/huggingface-sync-action@v0.0.4
      with:
        github_repo_id: DL4DS/ai_curriculum_assistant
        huggingface_repo_id: dl4ds/curriculum_advisor_dev
        repo_type: space
        space_sdk: static
        hf_token: ${{ secrets.HF_TOKEN }}
      